global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
      monitor: 'hospitial-app-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'patient-monitor'
    dns_sd_configs:
    - names:
      - 'tasks.patient'
      type: 'A'
      port: 2222
    metrics_path: '/actuator/prometheus'

