version: '3'

services:
  patient-database:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=Azerty123
      - MYSQL_DATABASE=Patient

  patient:
    image: patient:latest
    deploy:
      replicas: 2
    links:
      - patient-database
    depends_on:
      - patient-database
    volumes:
      - "/home/student/Documents/Java/spring/patient/:/app/"

  api-gateway:
    image: api-gateway:latest
    deploy:
      mode: global
    ports:
      - 80:8080    
    links:
      - patient
    depends_on:
      - patient
    volumes:
      - "/home/student/Documents/Java/spring/api_gateway/:/app/"
