swagger: '2.0'
host: 'localhost:8080'
# Information
info:
  description: Simple API to manipulate customers
  version: 1.0.0
  title: Simple Customer API
basePath: /
# REST calls
paths:
  /customer:
    # GET /customer
    get:
      summary: Get list of customers
      produces:
        - application/json
      responses:
        '200':
          description: Successful request
          schema:
            type: array
            items:
              $ref: '#/definitions/Customer'
    # PUT /customer
    put:
      summary: Create a new customer
      produces:
        - application/json
      responses:
        '200':
          description: Successful request
        '400':
          description: Bad request
    # POST /customer
    post:
      summary: Update a customer
      produces:
        - application/json
      responses:
        '200':
          description: Success response
        '400':
          description: Bad request
  /customer/{id}:
    # GET /customer/{id}
    get:
      summary: Get a specific customer
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of customer to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successful request
          schema:
            type: object
            properties:
              id:
                type: integer
              firstName:
                type: string
              lastName: 
                type: string
              email: 
                type: string
        '406':
          description: Not Acceptable
        default:
          description: Bad Request
    # POST /customer/{id}
    post:
      summary: Delete a customer
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of customer to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success response
          schema:
            type: object
            properties:
              id:
                type: integer
              firstName:
                type: string
              lastName: 
                type: string
              email: 
                type: string
        default:
          description: Bad Request
# Models
definitions:
  Customer:
    type: object
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string